In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('data/movie/tmdb_5000_credits.csv')
df2 = pd.read_csv('data/movie/tmdb_5000_movies.csv')

In [4]:
df1.rename(columns={'movie_id':'id'}, inplace=True)
df1.columns

Index(['id', 'title', 'cast', 'crew'], dtype='object')

In [5]:
df_temp = df1[['id', 'cast', 'crew']]
df_temp.columns

Index(['id', 'cast', 'crew'], dtype='object')

In [6]:
df = df2.merge(df_temp, on='id')
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'cast', 'crew'],
      dtype='object')

In [7]:
df['overview'].head(5)

0    In the 22nd century, a paraplegic Marine is di...
1    Captain Barbossa, long believed to be dead, ha...
2    A cryptic message from Bond’s past sends him o...
3    Following the death of District Attorney Harve...
4    John Carter is a war-weary, former military ca...
Name: overview, dtype: object

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
Tfidf = TfidfVectorizer(stop_words='english')

In [9]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
ENGLISH_STOP_WORDS

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides',
           'between',
           'beyond',
           'bill',
           'both',
           'bottom',
           'but',
           'by',
           'call',
           'can',
           'cannot',
           'cant',
           'co',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'do',
           'done',
           'down',
           'due',
           'during',
           'each',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'few',
           'fifteen',
           'fifty',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'for',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'from',
           'front',
           'full',
           'further',
           'get',
           'give',
           'go',
           'had',
           'has',
           'hasnt',
           'have',
           'he',
           'hence',
           'her',
           'here',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'hers',
           'herself',
           'him',
           'himself',
           'his',
           'how',
           'however',
           'hundred',
           'i',
           'ie',
           'if',
           'in',
           'inc',
           'indeed',
           'interest',
           'into',
           'is',
           'it',
           'its',
           'itself',
           'keep',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'many',
           'may',
           'me',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'more',
           'moreover',
           'most',
           'mostly',
           'move',
           'much',
           'must',
           'my',
           'myself',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'no',
           'nobody',
           'none',
           'noone',
           'nor',
           'not',
           'nothing',
           'now',
           'nowhere',
           'of',
           'off',
           'often',
           'on',
           'once',
           'one',
           'only',
           'onto',
           'or',
           'other',
           'others',
           'otherwise',
           'our',
           'ours',
           'ourselves',
           'out',
           'over',
           'own',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'rather',
           're',
           'same',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'she',
           'should',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'so',
           'some',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'such',
           'system',
           'take',
           'ten',
           'than',
           'that',
           'the',
           'their',
           'them',
           'themselves',
           'then',
           'thence',
           'there',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'these',
           'they',
           'thick',
           'thin',
           'third',
           'this',
           'those',
           'though',
           'three',
           'through',
           'throughout',
           'thru',
           'thus',
           'to',
           'together',
           'too',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'under',
           'until',
           'up',
           'upon',
           'us',
           'very',
           'via',
           'was',
           'we',
           'well',
           'were',
           'what',
           'whatever',
           'when',
           'whence',
           'whenever',
           'where',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'which',
           'while',
           'whither',
           'who',
           'whoever',
           'whole',
           'whom',
           'whose',
           'why',
           'will',
           'with',
           'within',
           'without',
           'would',
           'yet',
           'you',
           'your',
           'yours',
           'yourself',
           'yourselves'})

In [10]:
df['overview'].isnull().any()

np.True_

In [11]:
df['overview'].isnull().sum()

np.int64(3)

In [12]:
df['overview'].fillna('' , inplace=True)

C:\Users\AIPM2\AppData\Local\Temp\ipykernel_4180\536417175.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overview'].fillna('' , inplace=True)

In [13]:
df['overview'].isnull().any()

np.False_

In [14]:
df['overview'].isnull().sum()

np.int64(0)

In [15]:
len(df['overview'])

4803

In [16]:
#BOW Bag of Words 생성
Tfidf_matrix = Tfidf.fit_transform(df['overview'])

In [17]:
Tfidf_matrix.shape

(4803, 20978)

In [18]:
#문장 유사도
from sklearn.metrics.pairwise import linear_kernel
cosine_sim = linear_kernel(Tfidf_matrix, Tfidf_matrix)

In [19]:
cosine_sim.shape

(4803, 4803)

In [20]:
cosine_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.01488159, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02160533, 0.01488159, ..., 1.        , 0.01609091,
        0.00701914],
       [0.        , 0.        , 0.        , ..., 0.01609091, 1.        ,
        0.01171696],
       [0.        , 0.        , 0.        , ..., 0.00701914, 0.01171696,
        1.        ]], shape=(4803, 4803))

In [21]:
df['title'].head()

0                                      Avatar
1    Pirates of the Caribbean: At World's End
2                                     Spectre
3                       The Dark Knight Rises
4                                 John Carter
Name: title, dtype: object

In [22]:
title ='Avatar'
df[df['title']=='Avatar'].index

Index([0], dtype='int64')

In [23]:
title ='Avatar'
idx = df[df['title']==title].index[0]
print(idx)

0

In [24]:
title ='John Carter'
idx = df[df['title']==title].index[0]
print(idx)

4

In [25]:
title ='John Carter'
idx = df[df['title']==title].index[0]
df.iloc[[idx]]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
cosine_sim[4]

array([0.        , 0.03336868, 0.        , ..., 0.00612609, 0.        ,
       0.        ], shape=(4803,))

In [27]:
test_cosine_sim = list(enumerate(cosine_sim[4]))
test_cosine_sim

[(0, np.float64(0.0)),
 (1, np.float64(0.033368675996424305)),
 (2, np.float64(0.0)),
 (3, np.float64(0.010433403719159351)),
 (4, np.float64(0.9999999999999998)),
 (5, np.float64(0.0)),
 (6, np.float64(0.009339192776152496)),
 (7, np.float64(0.037407042075763064)),
 (8, np.float64(0.0)),
 (9, np.float64(0.01714819056424443)),
 (10, np.float64(0.02015372184154536)),
 (11, np.float64(0.0)),
 (12, np.float64(0.03178129553727139)),
 (13, np.float64(0.0)),
 (14, np.float64(0.010712515993695904)),
 (15, np.float64(0.0)),
 (16, np.float64(0.045257098111540495)),
 (17, np.float64(0.020358841382635908)),
 (18, np.float64(0.016907757517459005)),
 (19, np.float64(0.016254574057966483)),
 (20, np.float64(0.00914487577692374)),
 (21, np.float64(0.01727519014981104)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.01651050909357743)),
 (25, np.float64(0.0)),
 (26, np.float64(0.0538746515929863)),
 (27, np.float64(0.05231039324590807)),
 (28, np.float64(0.025467489988822038)),
 (29, np.float64(0.016102329289885736)),
 (30, np.float64(0.0)),
 (31, np.float64(0.01112130271029684)),
 (32, np.float64(0.021415531407536444)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.015826523804524963)),
 (36, np.float64(0.0381036148024992)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.02124047042069265)),
 (40, np.float64(0.00768676619264308)),
 (41, np.float64(0.01978947253021744)),
 (42, np.float64(0.0)),
 (43, np.float64(0.015863240253729538)),
 (44, np.float64(0.0)),
 (45, np.float64(0.022783108397171153)),
 (46, np.float64(0.08574401380341932)),
 (47, np.float64(0.05837115580794347)),
 (48, np.float64(0.027291542501988043)),
 (49, np.float64(0.006661619072989001)),
 (50, np.float64(0.05348134003905951)),
 (51, np.float64(0.020303156755951995)),
 (52, np.float64(0.0200156467845625)),
 (53, np.float64(0.009283858002248853)),
 (54, np.float64(0.055073031440828375)),
 (55, np.float64(0.0)),
 (56, np.float64(0.019705548314540633)),
 (57, np.float64(0.0)),
 (58, np.float64(0.054437289544783836)),
 (59, np.float64(0.014107530611723554)),
 (60, np.float64(0.0)),
 (61, np.float64(0.0)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.023498148063470496)),
 (65, np.float64(0.009805867807909803)),
 (66, np.float64(0.0)),
 (67, np.float64(0.019190706170422227)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.01094440728890874)),
 (71, np.float64(0.0069811676473432675)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.0)),
 (75, np.float64(0.022943142552820633)),
 (76, np.float64(0.04563868300474624)),
 (77, np.float64(0.01613816783918202)),
 (78, np.float64(0.0)),
 (79, np.float64(0.025760454420038537)),
 (80, np.float64(0.0)),
 (81, np.float64(0.023055502664015293)),
 (82, np.float64(0.03199363546220082)),
 (83, np.float64(0.028302134677120096)),
 (84, np.float64(0.015367708891529573)),
 (85, np.float64(0.07927219338261442)),
 (86, np.float64(0.006837763027138118)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.0)),
 (91, np.float64(0.06511318345155809)),
 (92, np.float64(0.019392953319592822)),
 (93, np.float64(0.014362368494416106)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.018148157421771442)),
 (98, np.float64(0.026230631433396143)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.008401329648238235)),
 (102, np.float64(0.008264600510095794)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.04975088891450889)),
 (108, np.float64(0.043752278061972745)),
 (109, np.float64(0.00904550886236454)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.008616077306773266)),
 (113, np.float64(0.0232436032763467)),
 (114, np.float64(0.0)),
 (115, np.float64(0.04296474509718628)),
 (116, np.float64(0.006845348430513409)),
 (117, np.float64(0.02383924013893402)),
 (118, np.float64(0.004307772202327974)),
 (119, np.float64(0.0)),
 (120, np.float64(0.02063396385983972)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.017118286549121477)),
 (124, np.float64(0.0)),
 (125, np.float64(0.0052726074946179025)),
 (126, np.float64(0.0)),
 (127, np.float64(0.06404845195093839)),
 (128, np.float64(0.014785526097967284)),
 (129, np.float64(0.016373173519004035)),
 (130, np.float64(0.0)),
 (131, np.float64(0.013247495222260349)),
 (132, np.float64(0.016986814622034045)),
 (133, np.float64(0.009013912737246)),
 (134, np.float64(0.0)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.007624305016523995)),
 (138, np.float64(0.0)),
 (139, np.float64(0.0)),
 (140, np.float64(0.014621772405641194)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.006441374367745254)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.011442209453330259)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0)),
 (149, np.float64(0.0)),
 (150, np.float64(0.014514909084696942)),
 (151, np.float64(0.0)),
 (152, np.float64(0.0337894127869508)),
 (153, np.float64(0.0)),
 (154, np.float64(0.020238158756250166)),
 (155, np.float64(0.05465599273472925)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.06136006069574057)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0310376418629274)),
 (161, np.float64(0.0)),
 (162, np.float64(0.05810181561753072)),
 (163, np.float64(0.02455765274889435)),
 (164, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0)),
 (168, np.float64(0.01866531692929332)),
 (169, np.float64(0.06572494101819237)),
 (170, np.float64(0.014262203354444069)),
 (171, np.float64(0.020213553025880373)),
 (172, np.float64(0.0)),
 (173, np.float64(0.006426217684023491)),
 (174, np.float64(0.044059407675698686)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.009456290973925852)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.00592115948559236)),
 (183, np.float64(0.0)),
 (184, np.float64(0.014890046218071499)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.021570096830354435)),
 (191, np.float64(0.0)),
 (192, np.float64(0.04264162048414869)),
 (193, np.float64(0.014649147138545352)),
 (194, np.float64(0.0)),
 (195, np.float64(0.02434986534338656)),
 (196, np.float64(0.0)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.04573250153848858)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.03950100817441227)),
 (208, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.00805350235878616)),
 (212, np.float64(0.006514578034920522)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.0)),
 (221, np.float64(0.0)),
 (222, np.float64(0.017817525091440814)),
 (223, np.float64(0.02469657647746403)),
 (224, np.float64(0.012662616613306298)),
 (225, np.float64(0.014414400616726329)),
 (226, np.float64(0.0)),
 (227, np.float64(0.03220763022607363)),
 (228, np.float64(0.05095192690216123)),
 (229, np.float64(0.0)),
 (230, np.float64(0.02623367394148595)),
 (231, np.float64(0.014442290617753284)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.015145778094171853)),
 (235, np.float64(0.0)),
 (236, np.float64(0.020263192301588864)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0)),
 (241, np.float64(0.0067722890129990896)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.008711826055257733)),
 (246, np.float64(0.04171799726689648)),
 (247, np.float64(0.0)),
 (248, np.float64(0.014326342152548341)),
 (249, np.float64(0.0)),
 (250, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.02265922530400015)),
 (254, np.float64(0.006650792688227934)),
 (255, np.float64(0.012896368470763373)),
 (256, np.float64(0.02615391867618884)),
 (257, np.float64(0.030584604510354278)),
 (258, np.float64(0.003687806578639362)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.020104879387202026)),
 (262, np.float64(0.03546421485928934)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (266, np.float64(0.027922856347770603)),
 (267, np.float64(0.0)),
 (268, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.05289174055081866)),
 (271, np.float64(0.01774986014471247)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.019012012076864985)),
 (276, np.float64(0.02210070952010449)),
 (277, np.float64(0.005171953174037606)),
 (278, np.float64(0.02620492372756335)),
 (279, np.float64(0.0320445184668943)),
 (280, np.float64(0.013066707226628685)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.02551952695772625)),
 (287, np.float64(0.0)),
 (288, np.float64(0.013393761102071822)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.009622490529342706)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.059721269746251145)),
 (295, np.float64(0.013850948453916684)),
 (296, np.float64(0.0069639065859347996)),
 (297, np.float64(0.00935590260380906)),
 (298, np.float64(0.008486495818406884)),
 (299, np.float64(0.0)),
 (300, np.float64(0.03179698829721199)),
 (301, np.float64(0.0)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.03206725478560125)),
 (305, np.float64(0.03578394005663959)),
 (306, np.float64(0.007726185544930469)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.01399893758248774)),
 (311, np.float64(0.01324690348881613)),
 (312, np.float64(0.0)),
 (313, np.float64(0.032145106599792105)),
 (314, np.float64(0.0)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0782683431858148)),
 (323, np.float64(0.019866852649844356)),
 (324, np.float64(0.00603221501979096)),
 (325, np.float64(0.009715822571524414)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.02593549675040616)),
 (332, np.float64(0.0)),
 (333, np.float64(0.008838459012222235)),
 (334, np.float64(0.02363266602696133)),
 (335, np.float64(0.0)),
 (336, np.float64(0.00994266056124025)),
 (337, np.float64(0.025455855411282504)),
 (338, np.float64(0.0)),
 (339, np.float64(0.01745919496268492)),
 (340, np.float64(0.0)),
 (341, np.float64(0.020089065896757703)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.02207015132799061)),
 (345, np.float64(0.09079218287485014)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.0)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.02388360180558951)),
 (353, np.float64(0.0)),
 (354, np.float64(0.03257507459063306)),
 (355, np.float64(0.01398296085574484)),
 (356, np.float64(0.023825116200832504)),
 (357, np.float64(0.0)),
 (358, np.float64(0.008668311550706164)),
 (359, np.float64(0.0)),
 (360, np.float64(0.017953160345580043)),
 (361, np.float64(0.0)),
 (362, np.float64(0.03166834779008205)),
 (363, np.float64(0.006637103391835837)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.0)),
 (373, np.float64(0.07112394697975578)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.011407564144343877)),
 (386, np.float64(0.0)),
 (387, np.float64(0.0)),
 (388, np.float64(0.0)),
 (389, np.float64(0.014382221127457503)),
 (390, np.float64(0.009518669504911264)),
 (391, np.float64(0.010338566571052935)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.0)),
 (395, np.float64(0.023744536615487158)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.021640428173372625)),
 (401, np.float64(0.04116784642875)),
 (402, np.float64(0.010848228649015888)),
 (403, np.float64(0.007522745564060013)),
 (404, np.float64(0.06030226569885218)),
 (405, np.float64(0.035806187126134044)),
 (406, np.float64(0.005450345122455705)),
 (407, np.float64(0.0)),
 (408, np.float64(0.00943408436948973)),
 (409, np.float64(0.00649252029116795)),
 (410, np.float64(0.022792184308144295)),
 (411, np.float64(0.0)),
 (412, np.float64(0.0200452665286035)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.016649932651121663)),
 (419, np.float64(0.03489914389791733)),
 (420, np.float64(0.035787861690470546)),
 (421, np.float64(0.0)),
 (422, np.float64(0.013534774420783956)),
 (423, np.float64(0.0)),
 (424, np.float64(0.034264287563403384)),
 (425, np.float64(0.0)),
 (426, np.float64(0.035841745790640284)),
 (427, np.float64(0.0)),
 (428, np.float64(0.00881395376729767)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.02480344523639407)),
 (433, np.float64(0.0)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0406773490542124)),
 (440, np.float64(0.006149877872062611)),
 (441, np.float64(0.008310766329020815)),
 (442, np.float64(0.0)),
 (443, np.float64(0.048233119854634424)),
 (444, np.float64(0.01517739651407271)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.012290686404449021)),
 (448, np.float64(0.020485159072648758)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.06061066997406978)),
 (455, np.float64(0.0)),
 (456, np.float64(0.015086950229015695)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.018771137266414384)),
 (462, np.float64(0.03397453798799191)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0)),
 (473, np.float64(0.05849726730091015)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0)),
 (476, np.float64(0.010325034050201427)),
 (477, np.float64(0.016722562376129055)),
 (478, np.float64(0.010020389555722492)),
 (479, np.float64(0.00453351923752785)),
 (480, np.float64(0.020786849919204986)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.009022689106186584)),
 (487, np.float64(0.06275480086880951)),
 (488, np.float64(0.0)),
 (489, np.float64(0.011058500719038945)),
 (490, np.float64(0.0)),
 (491, np.float64(0.017190690781164652)),
 (492, np.float64(0.0)),
 (493, np.float64(0.020962975284714833)),
 (494, np.float64(0.0)),
 (495, np.float64(0.0)),
 (496, np.float64(0.010490520313642827)),
 (497, np.float64(0.0)),
 (498, np.float64(0.009074127017110283)),
 (499, np.float64(0.0)),
 (500, np.float64(0.05508082020613065)),
 (501, np.float64(0.008240613504248779)),
 (502, np.float64(0.03012948946746212)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0)),
 (505, np.float64(0.03328763225618516)),
 (506, np.float64(0.0)),
 (507, np.float64(0.014191435701753024)),
 (508, np.float64(0.012580275044897418)),
 (509, np.float64(0.028058077465183816)),
 (510, np.float64(0.008798340039474935)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.0)),
 (515, np.float64(0.02149129732384898)),
 (516, np.float64(0.0)),
 (517, np.float64(0.020812032843081626)),
 (518, np.float64(0.02649104953721125)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.005653536898355653)),
 (524, np.float64(0.014820667329577507)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.05952690460008954)),
 (530, np.float64(0.0)),
 (531, np.float64(0.021726289408211467)),
 (532, np.float64(0.011810503512878805)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.0)),
 (536, np.float64(0.0)),
 (537, np.float64(0.03377902642044296)),
 (538, np.float64(0.0)),
 (539, np.float64(0.03572180516147093)),
 (540, np.float64(0.0)),
 (541, np.float64(0.03323299762497831)),
 (542, np.float64(0.008835340675404414)),
 (543, np.float64(0.005596517067855569)),
 (544, np.float64(0.020366453236280717)),
 (545, np.float64(0.01555725652136555)),
 (546, np.float64(0.009686662719229003)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.0)),
 (550, np.float64(0.013101223367845674)),
 (551, np.float64(0.0)),
 (552, np.float64(0.01434179096939347)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.01950518411413811)),
 (556, np.float64(0.0)),
 (557, np.float64(0.010049499818067659)),
 (558, np.float64(0.0)),
 (559, np.float64(0.0)),
 (560, np.float64(0.0)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.02998913345697007)),
 (564, np.float64(0.024755682723938945)),
 (565, np.float64(0.0)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.007779224761962552)),
 (569, np.float64(0.0)),
 (570, np.float64(0.0)),
 (571, np.float64(0.01566136138668507)),
 (572, np.float64(0.0)),
 (573, np.float64(0.031029998052109386)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.008472125011248707)),
 (577, np.float64(0.0)),
 (578, np.float64(0.0)),
 (579, np.float64(0.022573111976213114)),
 (580, np.float64(0.0)),
 (581, np.float64(0.0900594125581888)),
 (582, np.float64(0.02283661362899101)),
 (583, np.float64(0.0)),
 (584, np.float64(0.0)),
 (585, np.float64(0.020808377614610907)),
 (586, np.float64(0.0060893260762652545)),
 (587, np.float64(0.02219851809042213)),
 (588, np.float64(0.02997208608157952)),
 (589, np.float64(0.0)),
 (590, np.float64(0.0)),
 (591, np.float64(0.00875961739639285)),
 (592, np.float64(0.04403661344701933)),
 (593, np.float64(0.0)),
 (594, np.float64(0.0)),
 (595, np.float64(0.03733671458175879)),
 (596, np.float64(0.012301153523295704)),
 (597, np.float64(0.0)),
 (598, np.float64(0.0)),
 (599, np.float64(0.005745275971666855)),
 (600, np.float64(0.0262104603548376)),
 (601, np.float64(0.0)),
 (602, np.float64(0.020774410692259423)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.021526892991432137)),
 (607, np.float64(0.04538169103402193)),
 (608, np.float64(0.0)),
 (609, np.float64(0.029938076466136387)),
 (610, np.float64(0.015169864172183698)),
 (611, np.float64(0.0)),
 (612, np.float64(0.011497175489593238)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.0)),
 (618, np.float64(0.020077916279963443)),

In [28]:
test_cosine_sim = sorted(test_cosine_sim, key=lambda x:x[1], reverse=True)
test_cosine_sim[:11]

[(4, np.float64(0.9999999999999998)),
 (1254, np.float64(0.20497253140891997)),
 (4161, np.float64(0.16370347641323713)),
 (2932, np.float64(0.12239400129620456)),
 (3349, np.float64(0.11887151040572358)),
 (1307, np.float64(0.11468689553107403)),
 (3068, np.float64(0.11237609168095009)),
 (345, np.float64(0.09079218287485014)),
 (581, np.float64(0.0900594125581888)),
 (2998, np.float64(0.08877535757173034)),
 (4274, np.float64(0.08576462030578072))]

In [29]:
test_cosine_sim = test_cosine_sim[1:11]
index = [i[0] for i in test_cosine_sim]
index

[1254, 4161, 2932, 3349, 1307, 3068, 345, 581, 2998, 4274]

In [30]:
df.loc[index, 'title']

1254                          Get Carter
4161         The Marine 4: Moving Target
2932                        Raising Cain
3349                           Desperado
1307                       The Hurricane
3068                         Rescue Dawn
345                          Rush Hour 2
581              Star Trek: Insurrection
2998                               Devil
4274    Eddie: The Sleepwalking Cannibal
Name: title, dtype: object

In [31]:
def def_cosine_sim():
    #BOW Bag of words 생성
    from sklearn.feature_extraction.text import TfidfVectorizer
    Tfidf = TfidfVectorizer(stop_words='english')
    df = pd.read_csv('data/movie/tmdb_5000_movies.csv')

    df.fillna({'overview':''}, inplace=True)
    Tfidf_matrix = Tfidf.fit_transform(df['overview'])

    #문장 유사도
    from sklearn.metrics.pairwise import linear_kernel
    cosine_sim = linear_kernel(Tfidf_matrix, Tfidf_matrix)
    return cosine_sim

In [32]:
sim = def_cosine_sim()
sim.shape

(4803, 4803)

In [33]:
df[['title']].head()

                                      title
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

In [34]:
title = 'Avatar'
idx = df[df['title']==title].index[0]
print(idx)

0

In [35]:
def recommend(title):
    import pickle
    df = pd.read_csv('data/movie/tmdb_5000_movies.csv')
    idx = df[df['title']==title].index[0]
    
    cosine_sim = pickle.load(open('data/movie/cosine_sim.pickle', 'rb'))
    sim = cosine_sim[idx]
    
    sim = list(enumerate(sim))
    sim = sorted(sim, key=lambda x:x[1], reverse=True)
    sim = sim[1:11]
    index = [x[0] for x in sim]
    return index

In [36]:
index = recommend('Avatar')
index

[3604, 2130, 634, 1341, 529, 1610, 311, 847, 775, 2628]

In [37]:
idx = recommend('Batman Forever')
df.loc[idx, 'title']

3                         The Dark Knight Rises
119                               Batman Begins
65                              The Dark Knight
428                              Batman Returns
210                              Batman & Robin
3854    Batman: The Dark Knight Returns, Part 2
1359                                     Batman
4343                                   Cry_Wolf
174                         The Incredible Hulk
9            Batman v Superman: Dawn of Justice
Name: title, dtype: object

In [38]:
cosine_sim = def_cosine_sim()
cosine_sim[:3]

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.01488159, 0.        ,
        0.        ]], shape=(3, 4803))

In [39]:
import pickle
pickle.dump(cosine_sim, open('data/movie/cosine_sim.pickle', 'wb'))

In [40]:
merge = df.copy()
merge.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'cast', 'crew'],
      dtype='object')

In [41]:
#장르, 키워드, 주연배우, 감독
merge.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'cast', 'crew'],
      dtype='object')

In [42]:
from ast import literal_eval
merge['genres'] = merge['genres'].apply(literal_eval)

In [43]:
g = merge.loc[0, 'genres']
type(g)

list

In [44]:
cols = ['cast', 'crew', 'keywords']
for col in cols:
    merge[col] = merge[col].apply(literal_eval)

In [45]:
import numpy as np
def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
    return np.nan

In [46]:
get_director(merge.loc[0, 'crew'])

'James Cameron'

In [47]:
merge['director'] = merge['crew'].apply(get_director)

In [48]:
merge['director'].head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4       Andrew Stanton
Name: director, dtype: object

In [49]:
merge['director'].isnull().sum()

np.int64(30)

In [50]:
merge.fillna({'director':''}, inplace=True)

In [51]:
merge['director'].isnull().sum()

np.int64(0)

In [52]:
merge.loc[0, 'cast']

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [53]:
def get_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]
        if len(names)>3:
            names = names[:3]
        return names
    return []

In [54]:
cols = ['cast', 'keywords', 'genres']
for col in cols:
    merge[col] = merge[col].apply(get_list)

In [55]:
merge[['title', 'director', 'cast', 'keywords', 'genres']].head()

,title,director,cast,keywords,genres
0,Avatar,James Cameron,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[culture clash, future, space war]","[Action, Adventure, Fantasy]"
1,Pirates of the Caribbean: At World's End,Gore Verbinski,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[ocean, drug abuse, exotic island]","[Adventure, Fantasy, Action]"
2,Spectre,Sam Mendes,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[spy, based on novel, secret agent]","[Action, Adventure, Crime]"
3,The Dark Knight Rises,Christopher Nolan,"[Christian Bale, Michael Caine, Gary Oldman]","[dc comics, crime fighter, terrorist]","[Action, Crime, Drama]"
4,John Carter,Andrew Stanton,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[based on novel, mars, medallion]","[Action, Adventure, Science Fiction]"

In [56]:
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i).replace(' ', '') for i in x]
    else:
        if isinstance(x, str):
            return str.lower(x).replace(' ', '')
        else: 
            return ''

In [57]:
cols = ['director', 'cast', 'keywords', 'genres']
for col in cols:
    merge[col] = merge[col].apply(clean_data)

In [58]:
merge[['title', 'director', 'cast', 'keywords', 'genres']].head()

,title,director,cast,keywords,genres
0,Avatar,jamescameron,"[samworthington, zoesaldana, sigourneyweaver]","[cultureclash, future, spacewar]","[action, adventure, fantasy]"
1,Pirates of the Caribbean: At World's End,goreverbinski,"[johnnydepp, orlandobloom, keiraknightley]","[ocean, drugabuse, exoticisland]","[adventure, fantasy, action]"
2,Spectre,sammendes,"[danielcraig, christophwaltz, léaseydoux]","[spy, basedonnovel, secretagent]","[action, adventure, crime]"
3,The Dark Knight Rises,christophernolan,"[christianbale, michaelcaine, garyoldman]","[dccomics, crimefighter, terrorist]","[action, crime, drama]"
4,John Carter,andrewstanton,"[taylorkitsch, lynncollins, samanthamorton]","[basedonnovel, mars, medallion]","[action, adventure, sciencefiction]"

In [59]:
def create_soup(x):
    str = x['director'] + ' '
    str += ' '.join(x['keywords']) + ' '
    str += ' '.join(x['cast']) + ' '
    str += ' '.join(x['genres']) + ' '
    return str

In [60]:
merge['soup'] = merge.apply(create_soup, axis=1)

In [61]:
merge['soup'].head()

0    jamescameron cultureclash future spacewar samw...
1    goreverbinski ocean drugabuse exoticisland joh...
2    sammendes spy basedonnovel secretagent danielc...
3    christophernolan dccomics crimefighter terrori...
4    andrewstanton basedonnovel mars medallion tayl...
Name: soup, dtype: object

In [62]:
merge.to_csv('data/movie/movies.csv', index=False)

In [63]:
merge['overview'].head()

0    In the 22nd century, a paraplegic Marine is di...
1    Captain Barbossa, long believed to be dead, ha...
2    A cryptic message from Bond’s past sends him o...
3    Following the death of District Attorney Harve...
4    John Carter is a war-weary, former military ca...
Name: overview, dtype: object

In [64]:
df_movie = pd.read_csv('data/movie/movies.csv')
df_movie['soup']

0       jamescameron cultureclash future spacewar samw...
1       goreverbinski ocean drugabuse exoticisland joh...
2       sammendes spy basedonnovel secretagent danielc...
3       christophernolan dccomics crimefighter terrori...
4       andrewstanton basedonnovel mars medallion tayl...
                              ...
4798    robertrodriguez unitedstates–mexicobarrier leg...
4799    edwardburns  edwardburns kerrybishé marshadiet...
4800    scottsmith date loveatfirstsight narration eri...
4801     danielhsia  danielhenney elizacoupe billpaxton
4802    brianherzlinger obsession camcorder crush drew...
Name: soup, Length: 4803, dtype: object

In [65]:
def def_cosine_sim2():
    #BOW Bag of words 생성
    from sklearn.feature_extraction.text import CountVectorizer
    counter = CountVectorizer(stop_words='english')

    df = pd.read_csv('data/movie/movies.csv')
    df.fillna({'soup':''}, inplace=True)
    counter_matrix = counter.fit_transform(df['soup'])

    #문장 유사도
    from sklearn.metrics.pairwise import linear_kernel
    cosine_sim = linear_kernel(counter_matrix, counter_matrix)
    return cosine_sim

In [66]:
import pickle
pickle.dump(cosine_sim, open('data/movie/cosine_sim.pickle', 'wb'))

In [67]:
cosine_sim2 = def_cosine_sim2()
pickle.dump(cosine_sim2, open('data/movie/cosine_sim2.pickle', 'wb'))

In [68]:
def recommend2(title):
    import pickle
    df = pd.read_csv('data/movie/tmdb_5000_movies.csv')
    idx = df[df['title']==title].index[0]
    
    cosine_sim = pickle.load(open('data/movie/cosine_sim2.pickle', 'rb'))
    sim = cosine_sim[idx]
    
    sim = list(enumerate(sim))
    sim = sorted(sim, key=lambda x:x[1], reverse=True)
    sim = sim[1:11]
    index = [x[0] for x in sim]
    return index

In [69]:
index = recommend2('Superman Returns')
df.loc[index, 'title']

14                                  Man of Steel
813                                     Superman
870                                  Superman II
9             Batman v Superman: Dawn of Justice
46                    X-Men: Days of Future Past
1139                           The Warrior's Way
1296                                Superman III
2433            Superman IV: The Quest for Peace
0                                         Avatar
1       Pirates of the Caribbean: At World's End
Name: title, dtype: object

In [70]:
df = pd.read_csv('data/movie/movies.csv')
df.loc[0, ['id', 'title']]

id        19995
title    Avatar
Name: 0, dtype: object

In [77]:
from tmdbv3api import Movie, TMDb
tmdb = TMDb()
tmdb.api_key='c668cda4cf75bf267ef2aeffa2da0341'
tmdb.language='ko-KR'
movie = Movie()

details = movie.details('19995')
title = details['title']
poster = 'https://image.tmdb.org/t/p/w500' + details['poster_path']
overview = details['overview']
print(title)
print(poster)
print(overview)

아바타
https://image.tmdb.org/t/p/w500/m5lCha2XcbDowDoYHPc0DTNaCPU.jpg
가까운 미래, 지구는 에너지 고갈 문제를 해결하기 위해 머나먼 행성 판도라에서 대체 자원을 채굴하기 시작한다. 하지만 판도라의 독성을 지닌 대기로 인해 자원 획득에 어려움을 겪게 된 인류는 판도라의 토착민 나비의 외형에 인간의 의식을 주입, 원격 조종이 가능한 새로운 생명체를 탄생시키는 프로그램을 개발한다. 한편 하반신이 마비된 전직 해병대원 제이크 설리는 아바타 프로그램에 참가할 것을 제안받는다. 그 곳에서 자신의 아바타를 통해 자유롭게 걸을 수 있게 된 제이크는 자원 채굴을 막으려는 나비의 무리에 침투하라는 임무를 부여받는데...